# Site settings

baseurl: "" # the subpath of your site, e.g. /portfolio
url: "" # the base hostname & protocol for your site
language: "" # language to set into html tag, default is en

# User settings

author: Marcus Oliveira
author-title: Full Stack Developer
gravatar: d36a082aacb53b6f76869748fb4b81d4
email: mso10br@gmail.com
github: marcussoliveira
linkedin: br.linkedin.com/in/marcussoliveira
bio: "Brazilian developer Delphi and C#.Net.
I'm majoring in Computer science and I have two Pos-graduate(Lato Sensu). 
I am Information Tecnology specialist and strategic  business and competitive intelligence.  
I've been worked since 1996, with Clipper Summer Language and then Dephi.  
Nowadays I'm stating working with Web Technology, like HMTL, BootStrap, NodeJs, WCF, C#.Net and so on. 

front-end:
  - name: HTML 5
    level: 3
  - name: CSS 3
    level: 2
  - name: JavaScript
    level: 1
  - name: jQuery
    level: 2
  - name: AngularJs
    level: 2
  - name: Bootstrap
    level: 2
  - name: Materialize CSS
    level: 2
  
back-end:
  - name: C#
    level: 3
  - name: Delphi
    level: 5 
  - name: Node.js
    level: 1
  - name: Java
    level: 1
  - name: SQL
    level: 4
  - name: Lua
    level: 2

mobile:
  - name: Delphi Mobile
    level: 2
  
db:
  - name: MySQL
    level: 4
  - name: PostgreSQL
    level: 3
  - name: MongoDB
    level: 1
  - name: SQL Server
    level: 4
  - name: Oracle
    level: 4
  - name: Firebird
    level: 3
  
others:
  - name: Web Services
    level: 3
  - name: REST
    level: 3
  - name: JEE, JSF, JPA, EJB, CDI
    level: 0
  - name: iReport, Jasper Reports
    level: 1
  - name: NHibernate
    level: 2
  - name: WebApi
    level: 2

## For more settings: https://jekyllrb.com/docs/configuration/

# exclude files if no need build
exclude: ['package.json', 'node_modules', 'README.md', 'LICENSE']

# Gems
gems: [jekyll-sitemap, bourbon]
